
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 205933403006-bpor9k9eoo211pelg8surprgo11jevt8.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://kffa9824affd9a.user-app.krampoline.com/login/oauth2/code/google
            scope:
              - email
              - profile
          kakao:
            client-id: aad9fffaff5b6655b991487c5ff8b445
            redirect-uri: https://k56733b335962a.user-app.krampoline.com/login/oauth2/callback/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  data:
    redis:
      host: localhost
      port: 6379
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: ENC(EO7qYXT+s8nB8MjIIzbdgylu39ZmMcORxrcHyFe1zo3/WusiDRp2DJBYiNHgF8em)
    username: ENC(xr6m+OzCYbuFcv1RPhsjpw==)
    password: ENC(91DfR8uWhet4vgXhB1dgc82CVp6whK+m)
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: create

jwt:
  secret: abcdegfhikmlmlmlmllmlmlmllmlmlllllllllllllllllll
  expiration: 3000

app:
  upload:
    dir: uploads/img

jasypt:
  encryptor:
    bean: jasyptStringEncryptor


kakao:
  rest:
    api:
      key: ENC(nblnVxukBtIi6C3vRCb6oYfZMZGOCi9lK+p+KtVkAYI0sr+4MGNnttYcrktuJgIq)