spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(SgyhNpimVFEoQv9a5MChlCiao3nJgYEjGxB/3KAtTlhYxEeZdrD3PzJ0Io2vnrLS)
            redirect-uri: https://k56733b335962a.user-app.krampoline.com/login/oauth2/callback/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  data:
    redis:
      host: localhost
      port: 6379
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: ${DATABASE_URL}
    username: ENC(WDRhDR82jagUGYf6sUMXeA==)
    password: ENC(oMm0+X9Ho72GSrmUJOb9bQ==)
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: validate

jwt:
  secret: ENC(7kZtvyRlzXjVdNHt8cyWg+1XRqosKTVcq+o1apX4xQmP2ZY2nnPkATLDev2IjZWT4orx4/T4bHuIcyqhssP6mg==)
  expiration: 3000

app:
  upload:
    dir: uploads/img

jasypt:
  encryptor:
    bean: jasyptStringEncryptor